### ISSUE TITLE
FNC3

### ISSUE THREAD

**Issue by julienvincent** [ramamurthynagaraj/RNZxing#2]
Is it possible to generate barcodes with FNC3 values?

**Comment by ramamurthynagaraj** [comment]
Hi, I just tested out in the Example provided. It works with FNC3 values.
You can try it out by using 'Welcome to React Native! with FNC3: Ȩ' in https://github.com/ramamurthynagaraj/RNZxing/blob/14dab5ec12b7444c2b7dd0ec52ae87a82fac5583/Example/barcode.js#L14

**Comment by julienvincent** [comment]
Yes I realized I have been using incorrect characters to represent FNC3. Thanks for the help though :)
